"""Sample fixtures for normalization guardrails and tests."""

from __future__ import annotations

FIXTURE_ROWS = [
    {"id": "fx-001", "raw_name": "ACME FACILITY SERVICES, INC.", "canonical": "Acme Facility Services"},
    {"id": "fx-002", "raw_name": "Acme Cleaning LLC - Dallas", "canonical": "Acme Cleaning"},
    {"id": "fx-003", "raw_name": "The Sterling Group Holdings, LLC", "canonical": "Sterling Group"},
    {"id": "fx-004", "raw_name": "BrightWave Solar Ltd (Austin HQ)", "canonical": "BrightWave Solar"},
    {"id": "fx-005", "raw_name": "Northstar Pest Control of Tampa", "canonical": "Northstar Pest Control"},
    {"id": "fx-006", "raw_name": "Blue Horizon Marine Services Pty Ltd", "canonical": "Blue Horizon Marine Services"},
    {"id": "fx-007", "raw_name": "Acme Facility Care (West Region)", "canonical": "Acme Facility Care"},
    {"id": "fx-008", "raw_name": "NovaTech Robotics GmbH", "canonical": "NovaTech Robotics"},
    {"id": "fx-009", "raw_name": "Atlas Industrial Cleaning & Co.", "canonical": "Atlas Industrial Cleaning"},
    {"id": "fx-010", "raw_name": "GreenLeaf Landscaping - Phoenix East", "canonical": "GreenLeaf Landscaping"},
    {"id": "fx-011", "raw_name": "Precision Analytics (New)", "canonical": "Precision Analytics"},
    {"id": "fx-012", "raw_name": "Summit Bio Labs, Inc.", "canonical": "Summit Bio Labs"},
    {"id": "fx-013", "raw_name": "Coastal Pest & Lawn LLC", "canonical": "Coastal Pest & Lawn"},
    {"id": "fx-014", "raw_name": "Valor Security Solutions (US)", "canonical": "Valor Security Solutions"},
    {"id": "fx-015", "raw_name": "Unity Mechanical Services, LLP", "canonical": "Unity Mechanical Services"},
    {"id": "fx-016", "raw_name": "Evergreen BioWaste Removal - Seattle", "canonical": "Evergreen BioWaste Removal"},
    {"id": "fx-017", "raw_name": "Horizon Facility Support, LLC - HQ", "canonical": "Horizon Facility Support"},
    {"id": "fx-018", "raw_name": "Prime Pest Elimination Co.", "canonical": "Prime Pest Elimination"},
    {"id": "fx-019", "raw_name": "Beacon Analytics Incorporated", "canonical": "Beacon Analytics"},
    {"id": "fx-020", "raw_name": "Summit Window Care, L.L.C.", "canonical": "Summit Window Care"},
    {"id": "fx-021", "raw_name": "BrightStar Cleaners - Chicago (Loop)", "canonical": "BrightStar Cleaners"},
    {"id": "fx-022", "raw_name": "Crystal Waters Pool & Spa Ltd", "canonical": "Crystal Waters Pool & Spa"},
    {"id": "fx-023", "raw_name": "Atlas Roofing Solutions, Inc", "canonical": "Atlas Roofing Solutions"},
    {"id": "fx-024", "raw_name": "MegaCorp Holdings PLC", "canonical": "MegaCorp Holdings"},
    {"id": "fx-025", "raw_name": "Blue Ridge Builders (Charlotte)", "canonical": "Blue Ridge Builders"},
    {"id": "fx-026", "raw_name": "Sunrise Logistics Oy", "canonical": "Sunrise Logistics"},
    {"id": "fx-027", "raw_name": "Starlight Event Rentals - NYC", "canonical": "Starlight Event Rentals"},
    {"id": "fx-028", "raw_name": "Velocity Medical Transport P.C.", "canonical": "Velocity Medical Transport"},
    {"id": "fx-029", "raw_name": "EcoWise Pest Professionals Sdn Bhd", "canonical": "EcoWise Pest Professionals"},
    {"id": "fx-030", "raw_name": "Heritage Real Estate Group GmbH", "canonical": "Heritage Real Estate Group"},
    {"id": "fx-031", "raw_name": "Skyline IT Services Inc (Remote)", "canonical": "Skyline IT Services"},
    {"id": "fx-032", "raw_name": "Riverbend Facility Care - South", "canonical": "Riverbend Facility Care"},
    {"id": "fx-033", "raw_name": "Harbor City Cleaners, LLC - Zone 4", "canonical": "Harbor City Cleaners"},
    {"id": "fx-034", "raw_name": "Precision Engineering BV", "canonical": "Precision Engineering"},
    {"id": "fx-035", "raw_name": "Silverline Consulting GmbH & Co. KG", "canonical": "Silverline Consulting"},
    {"id": "fx-036", "raw_name": "Mosaic Creative Studio (EMEA)", "canonical": "Mosaic Creative Studio"},
    {"id": "fx-037", "raw_name": "Quantum Labs Pty. Ltd.", "canonical": "Quantum Labs"},
    {"id": "fx-038", "raw_name": "Evergreen Landscaping LLC - Boise", "canonical": "Evergreen Landscaping"},
    {"id": "fx-039", "raw_name": "Redwood Analytics - San Jose HQ", "canonical": "Redwood Analytics"},
    {"id": "fx-040", "raw_name": "Cedar Grove Nursing P.A.", "canonical": "Cedar Grove Nursing"},
    {"id": "fx-041", "raw_name": "Aurora Bio Labs SRL", "canonical": "Aurora Bio Labs"},
    {"id": "fx-042", "raw_name": "BrightSide Clean LLC (Franchise)", "canonical": "BrightSide Clean"},
    {"id": "fx-043", "raw_name": "Summit Pest Solutions LLP", "canonical": "Summit Pest Solutions"},
    {"id": "fx-044", "raw_name": "Lakeview Property Mgmt - Midtown", "canonical": "Lakeview Property Mgmt"},
    {"id": "fx-045", "raw_name": "OpenSky Security & Co.", "canonical": "OpenSky Security"},
    {"id": "fx-046", "raw_name": "Cardinal Janitorial Services Inc.", "canonical": "Cardinal Janitorial Services"},
    {"id": "fx-047", "raw_name": "Phoenix Pest & Turf LLC - Mesa", "canonical": "Phoenix Pest & Turf"},
    {"id": "fx-048", "raw_name": "TrueNorth Facility Solutions - HQ", "canonical": "TrueNorth Facility Solutions"},
    {"id": "fx-049", "raw_name": "Edgewater Marine Repair Company", "canonical": "Edgewater Marine Repair"},
    {"id": "fx-050", "raw_name": "Cascade Wellness Group LTD", "canonical": "Cascade Wellness Group"},
]

